### ISSUE TITLE
"Override WordPress avatars" option doesn't appear to work with comments

### ISSUE THREAD

**Issue by thameera** [auth0/wp-auth0#355] opened 2017-12-11 11:20 UTC
Even when the "Override WordPress avatars" in the Features tab is turned on, the picture for the comments section, etc still seem to use Gravatar instead of user's picture. However the user's profile page (in admin panel) shows the correct picture.

**Comment by howarddc** [comment] 2017-12-11 18:06
Here's the fix:

/plugins/auth0/WP_Auth0.php Line 160, add:

`if (is_object($id_or_email) && isset($id_or_email->user_id)) $id_or_email=$id_or_email->user_id;
`

The issue is that the comments version of this filter sends the full WP_Comment object as the second param to get_avatar, and the code was assuming it would always be an integer user ID. Instead, the user ID is a property of the object.

**Comment by joshcanhelp** [comment] 2018-01-22 16:31
From /wp-includes/pluggable.php L:2550:

"The Gravatar to retrieve. Accepts a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object."

Assigning to myself to address in the next next release.

**Closed** 2018-02-16 18:37 UTC
Labels: bug
