### ISSUE TITLE
SSO login failing when not using implicit flow

### ISSUE THREAD

**Issue by nicosabena** [auth0/wp-auth0#363] opened 2018-01-16 04:16 UTC
When you enable the **Single Sign On (SSO)** toggle in the **Features** settings of the plugin, [some client javascript is rendered](https://github.com/auth0/wp-auth0/blob/dev/templates/auth0-sso-handler-lock10.php) to `checkSession` and see if a valid SSO session is available at Auth0, to log the user in automatically without prompting for credentials.

The above flow is failing when there's a valid SSO session at Auth0, causing the plugin code to display:

> There was a problem with your log in

and logging a "Wrong number of segments" error in the internal plugin logs:

![image](https://user-images.githubusercontent.com/5222181/34970677-dd70ac5c-fac9-11e7-9338-dbb0a442f4f8.png)

The `checkSession` callback does not have an `idToken` in the `authResult`, which causes the `Wrong number of segments` error described above. 

![image](https://user-images.githubusercontent.com/5222181/34971289-afe0635a-facd-11e7-93cb-58c119e12aa9.png)

This is because the call to `checkSession` uses `responseType: 'code'` when implicit flow is turned off, and that response type is not supported by `checkSession`.

```javascript
  var options = <?php echo json_encode( $lock_options->get_sso_options() ); ?>;
```

results into:

```javascript
  var options = {"scope":"openid ","responseType":"code","redirectUri":"http:\/\/dev-nicotest1.pantheonsite.io\/index.php?auth0=1","state":"xxxx","nonce":"nonce"};
```

`responseType: 'code'` is not valid in `checkSession`:

https://github.com/auth0/auth0.js/blob/308d55f9f0a8c6fa2f46cd61cf7be2917a8fa647/src/web-auth/index.js#L389-L391

To reproduce:

- Make sure the WP site is working with the Auth0 plugin
- Enable the **Single Sign On (SSO)** toggle in the plugin settings
- Disable the **Implicit flow** toggle.
- Log in with the Auth0 plugin into the WP site. This will create a session both in the WP site and in Auth0.
- Clear the cookies for the WP site (but leave the ones in Auth0). This will log you out of the WP site.
- Go to `/wp-login.php` into the WP site. The rendered HTML will do a `checkSession` call (which will find a session in Auth0). You'll get "There was a problem with your log in"

**Comment by cocojoe** [comment] 2018-01-16 10:29
Thanks @nicosabena 
@joshcanhelp let's talk to Luis today.

**Comment by joshcanhelp** [comment] 2018-01-23 17:39
@nicosabena - Just circling back to this now. 

So is this just a matter of passing a different `responseType` to `checkSession()`?

I tried your reproduction steps and did not see the same error log entry, with Implicit turned off or turned on. I tried 3.4.0 and the latest branch I'm working on and neither had that issue. Is it possible the Lock or Auth.js upgrade in 3.4.0 addressed this?

**Comment by cocojoe** [comment] 2018-01-23 22:19
@luisrudge just wanted to run past you ☝️ thx

**Comment by luisrudge** [comment] 2018-01-23 23:44
yeah, checkSession doesn't support responseType:code, because it uses response_mode:web_message, which renders the response inside the page itself (there's no redirect).

**Comment by joshcanhelp** [comment] 2018-01-24 16:40
@luisrudge - Thanks for chiming in here. 

Is there a `responseType` we should always be using here instead of what comes from the WP settings?

**Comment by luisrudge** [comment] 2018-01-24 16:44
`token` or `token id_token` if you want the idToken

**Comment by jmangelo** [comment] 2018-01-26 14:23
Instead of always using a different response type isn't just a case of removing that snippet? When I enable that option Lock 11 will perform a similar call to what that snippet is trying to perform.

**Comment by joshcanhelp** [comment] 2018-01-29 20:14
@nicosabena - The latest version of the plugin is now using Lock 11.1, which might be affecting my ability to test this. I've tried a number of different ways to get this to work, understanding the `responseType` mismatch, but I'm not able to replicate what you're reporting. 

@luisrudge - Easy enough to change on my end but any thoughts on what @jmangelo is saying above? Do we need to do a `checkSession` on that page at all? 

I'm curious if this report is related at all:
https://wordpress.org/support/topic/stop-dont-download-the-plugin-doesnt-work/#post-9911684

**Comment by luisrudge** [comment] 2018-01-29 21:30
@joshcanhelp  It depends on what the page is doing. Lock will do a checkSession to see if needs to show the "Last time you logged in with" screen. It won't auto-login the user. If you want to auto-login the user, you need to do that by yourself in that page, yes.

**Comment by joshcanhelp** [comment] 2018-01-29 22:27
Pinging @cocojoe and @glena for some context. 

What's the expected behavior? If it means less code operating in this plugin, I would lean heavily towards removing this code and relying on default Lock behavior.

`checkSession` is used in these two templates:

https://github.com/auth0/wp-auth0/blob/master/templates/auth0-sso-handler-lock10.php
https://github.com/auth0/wp-auth0/blob/master/templates/auth0-sso-handler.php

... the latter of which is not included anywhere currently.

**Comment by joshcanhelp** [comment] 2018-01-30 02:53
Thanks @glena, will do.

@nicosabena - once you’re out of the woods, it would be great to get you a version of the plugin you can test that will include these changes and the Lock upgrade

**Comment by saltukalakus** [comment] 2018-01-30 05:54
ZD # 34725

**Comment by codyayers** [comment] 2018-02-01 19:23
Could we get an update on when this will be fixed?

**Comment by joshcanhelp** [comment] 2018-02-01 20:32
@codyayers - This specific fix or SSO in general? We've been talking internally and need to come up with a solution that's going to work long-term. We're aware of what needs to be done here, just want to make sure the solution works well now and going forward. 

Getting this operating 💯 is our highest priority for the plugin right now.

**Comment by codyayers** [comment] 2018-02-01 23:02
@joshcanhelp this specific fix. I'm happy to hear this, just would like to know if any ETA could be provided. Thanks!

**Comment by joshcanhelp** [comment] 2018-02-01 23:30
@codyayers - This particular fix won't make much of a difference as the check this is trying to do is now happening in Lock 11 (which the latest plugin version will upgrade you to). 

That said, here is the one-line change if you want to give it a test on your end:

https://github.com/auth0/wp-auth0/compare/issue-363-experiment

If this has a positive effect, happy to include it in the next release (2 weeks max).

**Comment by joshcanhelp** [comment] 2018-02-02 18:19
Checking in again here ... that compare branch above expanded by 4 lines but I've got it working now, auto-logging in if the WP session ends before the Auth0 one does. It would be great to get someone to test this out against another set of config options but it's a simple fix and I can fast-track this into the next release coming very soon.

**Comment by codyayers** [comment] 2018-02-02 18:55
@joshcanhelp these changes: https://github.com/auth0/wp-auth0/compare/issue-363-experiment appear to resolve the problem completely for us! 👍

**Comment by codyayers** [comment] 2018-02-02 18:57
Shoot.. I take that back.. worked the first time, but now it doesn't seem to be... Will continue testing.

**Comment by joshcanhelp** [comment] 2018-02-02 19:01
@codyayers - Error messages seen, logged in wp-admin, and logged in the dashboard are helpful, along with steps to reproduce, of course. Might be best to start with a clean browser session, i.e. cleared cookies, but not incognito.

**Comment by joshcanhelp** [comment] 2018-02-02 21:01
@codyayers - Likely to be a related issue. I had it on my list to walk through that once this process was confirmed. 

Stay tuned ... and thank you for testing!

**Comment by joshcanhelp** [comment] 2018-02-02 22:52
@codyayers - Similar fix for SLO, same compare link as before, single-line fix:

https://github.com/auth0/wp-auth0/compare/issue-363-experiment

I need to setup a network of sites to test this properly so not ready for release but the changes in that compare shouldn't hurt anything or introduce any new issues.

**Comment by joshcanhelp** [comment] 2018-02-08 13:51
Tested on my end and confirmed it works as expected. If anyone else has any feedback 👍 👎 on this, that would be great. Otherwise, I'm going to put this into a PR and get it ready for release next week in 3.5.2.

Thanks everyone!

**Closed** 2018-02-16 18:37 UTC
Labels: CH: Fixed
