### ISSUE TITLE
Dashboard widget, Uninitialized string offset

### ISSUE THREAD

**Issue by benplum** [auth0/wp-auth0#232] opened 2016-08-29 17:37 UTC
Using the dashboard widget slows the dashboard page load and consistently fires an error with this line: 

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_Serializer.php#L8

**Comment by glena** [comment] 2016-09-05 14:20
@benplum I am not able to reproduce it. 

are you using `get_currentauth0user` somewhere?

**Comment by glena** [comment] 2016-09-05 14:28
added some validations before unserializing just in case.
It will be released by EOW

**Comment by glena** [comment] 2016-09-07 14:31
I will release `3.2.5` in a couple of hours. I am closing this one but reopen after the update if you need.

**Closed by glena** 2016-09-07 14:31 UTC
